{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0.0",
    "title": "Ioasys Challenge",
    "description": "Ioasys Challenge Documentation",
    "termsOfService": "http://swagger.io/terms/",
    "contact": { "name": "https://github.com/RaulAquino207" },
    "license": { "name": "MIT" }
  },
  "servers" : [
    {
      "url" : "http://localhost:5000",
      "description" : "Enterprise Resource Planning API"
    }
  ],
  "paths": {
    "/health" : {
      "get" : {
        "summary" : "Show if the backend in general is ok.",
        "description" : "This route has the property of showing if the backend is ok in general.",
        "tags" : ["API"],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "type" : "object"
              }
            }
          }
        }
      }
    },
    "/login" : {
      "post" : {
        "sumary" : "",
        "description" : "",
        "tags" : ["Authenticate"],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/Authenticate"
              },
              "examples" : {
                "authenticate" : {
                  "value" : {
                    "email" : "admin@email.com",
                    "password" : "12345678"
                  }
                }
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "type" : "object"
              }
            }
          }
        }
      }
    },
    "/findDepartmentByEnterpriseId/{id}" : {
      "get" : {
        "summary" : "",
        "description" : "",
        "tags" : ["Department"],
        "parameters" : [
          {
            "name" : "id",
            "in" : "path",
            "description" : "department id",
            "required" : "true"
          }
        ],
        "security" : [{"bearerAuth" : []}],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "type" : "array"
              }
            }
          },
          "400" : {
            "description" : "Not found",
            "content" : {
              "application/json" : {
                "type" : "object"
              }
            }
          }
        }
      }
    },
    "/deleteDepartment/{id}" : {
      "delete" : {
        "summary" : "",
        "description" : "",
        "tags" : ["Department"],
        "parameters" : [
          {
            "name" : "id",
            "in" : "path",
            "description" : "department id",
            "required" : "true"
          }
        ],
        "security" : [{"bearerAuth" : []}],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "type" : "object"
              }
            }
          },
          "400" : {
            "description" : "Not found",
            "content" : {
              "application/json" : {
                "type" : "object"
              }
            }
          }
        }
      }
    },
    "/deleteUser/{id}" : {
      "delete" : {
        "summary" : "",
        "description" : "",
        "tags" : ["User"],
        "parameters" : [
          {
            "name" : "id",
            "in" : "path",
            "description" : "user id",
            "required" : "true"
          }
        ],
        "security" : [{"bearerAuth" : []}],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "type" : "object"
              }
            }
          },
          "400" : {
            "description" : "Not found",
            "content" : {
              "application/json" : {
                "type" : "object"
              }
            }
          }
        }
      }
    },
    "/changeDepartmentName/{id}" : {
      "put" : {
        "summary" : "",
        "description" : "",
        "tags" : ["Department"],
        "parameters" : [
          {
            "name" : "id",
            "in" : "path",
            "description" : "department id",
            "required" : "true"
          }
        ],
        "security" : [{"bearerAuth" : []}],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/AlterDepartment"
              },
              "examples" : {
                "user" : {
                  "value" : {
                    "departmentName" : "RH"
                  }
                }
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "type" : "object"
              }
            }
          },
          "400" : {
            "description" : "Not found",
            "content" : {
              "application/json" : {
                "type" : "object"
              }
            }
          }
        }
      }
    },
    "/changeUserInfo/{id}" : {
      "put" : {
        "summary" : "",
        "description" : "",
        "tags" : ["User"],
        "parameters" : [
          {
            "name" : "id",
            "in" : "path",
            "description" : "user id",
            "required" : "true"
          }
        ],
        "security" : [{"bearerAuth" : []}],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/AlterUser"
              },
              "examples" : {
                "user" : {
                  "value" : {
                    "userName" : "NAME 1",
                    "email" : "test1@email.com",
                    "password" : "12345678",
                    "role" : "ADMIN",
                    "department" : "1"
                  }
                }
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "type" : "object"
              }
            }
          },
          "400" : {
            "description" : "Not found",
            "content" : {
              "application/json" : {
                "type" : "object"
              }
            }
          }
        }
      }
    },
    "/findUserByEnterpriseId/{id}" : {
      "get" : {
        "summary" : "",
        "description" : "",
        "tags" : ["User"],
        "parameters" : [
          {
            "name" : "id",
            "in" : "path",
            "description" : "enterprise id",
            "required" : "true"
          }
        ],
        "security" : [{"bearerAuth" : []}],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "type" : "array"
              }
            }
          },
          "400" : {
            "description" : "Not found",
            "content" : {
              "application/json" : {
                "type" : "object"
              }
            }
          }
        }
      }
    },
    "/findUserByDepartment/{id}" : {
      "get" : {
        "summary" : "",
        "description" : "",
        "tags" : ["User"],
        "parameters" : [
          {
            "name" : "id",
            "in" : "path",
            "description" : "department id",
            "required" : "true"
          }
        ],
        "security" : [{"bearerAuth" : []}],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "type" : "array"
              }
            }
          },
          "400" : {
            "description" : "Not found",
            "content" : {
              "application/json" : {
                "type" : "object"
              }
            }
          }
        }
      }
    },
    "/version" : {
      "get" : {
        "summary" : "API version",
        "description" : "Behind what is the current version of the backend.",
        "tags" : ["API"],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "type" : "object"
              }
            }
          }
        }
      }
    },
    "/registerEnterprise" : {
      "post" : {
        "sumary" : "",
        "description" : "",
        "tags" : ["Enterprise"],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/Enterprise"
              },
              "examples" : {
                "enterprise" : {
                  "value" : {
                    "enterpriseName" : "Enterprise 1",
                    "userName" : "Name 1",
                    "email" : "admin@email.com",
                    "password" : "12345678",
                    "passwordConfirm" : "12345678"
                  }
                }
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "type" : "object"
              }
            }
          }
        }
      }
    },
    "/registerDepartment" : {
      "post" : {
        "sumary" : "",
        "description" : "",
        "tags" : ["Department"],
        "security" : [{"bearerAuth" : []}],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/Department"
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "type" : "object"
              }
            }
          }
        }
      }
    },
    "/registerUser" : {
      "post" : {
        "sumary" : "",
        "description" : "",
        "tags" : ["User"],
        "security" : [{"bearerAuth" : []}],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/User"
              },
              "examples" : {
                "user" : {
                  "value" : {
                    "userName" : "NAME 1",
                    "email" : "test1@email.com",
                    "password" : "12345678",
                    "passwordConfirm" : "12345678",
                    "roleTag" : "ADMIN",
                    "enterpriseId" : "1",
                    "departmentId" : "1"
                  }
                }
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "type" : "object"
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "Enterprise" : {
        "type" : "object",
        "properties" : {
          "enterpriseName" : {
            "type" : "string"
          },
          "userName" : {
            "type" : "string"
          },
          "email" : {
            "type" : "string"
          },
          "password" : {
            "type" : "string"
          },
          "passwordConfirm" : {
            "type" : "string"
          }
        }
      },

      "Department" : {
        "type" : "object",
        "properties" : {
          "departmentName" : {
            "type" : "string"
          },
          "enterpriseId" : {
            "type" : "number"
          }
        }
      },

      "AlterUser" : {
        "type" : "object",
        "properties" : {
          "userName" : {
            "type" : "string"
          },
          "email" : {
            "type" : "string"
          },
          "password" : {
            "type" : "string"
          },
          "roleTag" : {
            "type" : "string"
          },
          "departmentId" : {
            "type" : "number"
          }
        }
      },

      "AlterDepartment" : {
        "type" : "object",
        "properties" : {
          "departmentName" : {
            "type" : "string"
          }
        }
      },

      "User" : {
        "type" : "object",
        "properties" : {
          "userName" : {
            "type" : "string"
          },
          "email" : {
            "type" : "string"
          },
          "password" : {
            "type" : "string"
          },
          "passwordConfirm" : {
            "type" : "string"
          },
          "roleTag" : {
            "type" : "string"
          },
          "enterpriseId" : {
            "type" : "number"
          },
          "departmentId" : {
            "type" : "number"
          }
        }
      },

      "Authenticate" : {
        "type" : "object",
        "properties" : {
          "email" : {
            "type" : "string"
          },
          "password" : {
            "type" : "string"
          }
        }
      }
    },
    "securitySchemes" : {
      "bearerAuth" : {
        "type" : "http",
        "scheme" : "bearer",
        "bearerFormat" : "JWT"
      }
    }
  }
}
